<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>VerseOff.Customization</AssemblyName>
    <RootNamespace>VerseOff.Customization</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../VerseOff.Domain/VerseOff.Domain.csproj" />
    <ProjectReference Include="../VerseOff.Metadata/VerseOff.Metadata.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="16.0.0" />
  </ItemGroup>

</Project>
