// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerseOff.Storage;

#nullable disable

namespace VerseOff.Storage.Migrations
{
    [DbContext(typeof(VerseOffDbContext))]
    [Migration("20260906210521_AddTimelineCache")]
    partial class AddTimelineCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("VerseOff.Storage.CachedRecordEntity", b =>
                {
                    b.Property<string>("TableLogicalName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Etag")
                        .HasColumnType("TEXT");

                    b.Property<long>("ModifiedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecuritySnapshotVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.HasKey("TableLogicalName", "RecordId");

                    b.HasIndex("SyncState");

                    b.ToTable("CachedRecords");
                });

            modelBuilder.Entity("VerseOff.Storage.EntitlementLeaseEntity", b =>
                {
                    b.Property<Guid>("LeaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppModuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserObjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("LeaseId");

                    b.HasIndex("UserObjectId", "DeviceId", "ExpiresAt");

                    b.ToTable("EntitlementLeases");
                });

            modelBuilder.Entity("VerseOff.Storage.OutboxEntryEntity", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseEtag")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableLogicalName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserObjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("OperationId");

                    b.HasIndex("State", "CreatedAt");

                    b.ToTable("OutboxEntries");
                });

            modelBuilder.Entity("VerseOff.Storage.TimelineAttachmentEntity", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Etag")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedStorageReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TimelineRecordId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransferState")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttachmentId");

                    b.HasIndex("TimelineRecordId");

                    b.ToTable("TimelineAttachments");
                });

            modelBuilder.Entity("VerseOff.Storage.TimelinePartyEntity", b =>
                {
                    b.Property<Guid>("TimelineRecordId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartyIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipationTypeMask")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PartyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartyLogicalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedDetailsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TimelineRecordId", "PartyIndex");

                    b.ToTable("TimelineParties");
                });

            modelBuilder.Entity("VerseOff.Storage.TimelineRecordEntity", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Etag")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtectedPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordKind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RegardingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegardingTable")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecuritySnapshotVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("SortDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableLogicalName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("RecordId");

                    b.HasIndex("SecuritySnapshotVersion");

                    b.HasIndex("RegardingTable", "RegardingId", "SortDate");

                    b.ToTable("TimelineRecords");
                });

            modelBuilder.Entity("VerseOff.Storage.TimelineAttachmentEntity", b =>
                {
                    b.HasOne("VerseOff.Storage.TimelineRecordEntity", null)
                        .WithMany()
                        .HasForeignKey("TimelineRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VerseOff.Storage.TimelinePartyEntity", b =>
                {
                    b.HasOne("VerseOff.Storage.TimelineRecordEntity", null)
                        .WithMany()
                        .HasForeignKey("TimelineRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
