// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerseOff.Storage;

#nullable disable

namespace VerseOff.Storage.Migrations
{
    [DbContext(typeof(VerseOffDbContext))]
    [Migration("20260906205536_InitialDeviceStore")]
    partial class InitialDeviceStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("VerseOff.Storage.CachedRecordEntity", b =>
                {
                    b.Property<string>("TableLogicalName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Etag")
                        .HasColumnType("TEXT");

                    b.Property<long>("ModifiedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecuritySnapshotVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.HasKey("TableLogicalName", "RecordId");

                    b.HasIndex("SyncState");

                    b.ToTable("CachedRecords");
                });

            modelBuilder.Entity("VerseOff.Storage.EntitlementLeaseEntity", b =>
                {
                    b.Property<Guid>("LeaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppModuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserObjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("LeaseId");

                    b.HasIndex("UserObjectId", "DeviceId", "ExpiresAt");

                    b.ToTable("EntitlementLeases");
                });

            modelBuilder.Entity("VerseOff.Storage.OutboxEntryEntity", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseEtag")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableLogicalName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserObjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("OperationId");

                    b.HasIndex("State", "CreatedAt");

                    b.ToTable("OutboxEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
